### PR TITLE
Adding SQL requests

### PR DESCRIPTION
**Pull request by peotr26**
Here is the pull request for the 30 requests. If you find that 2 (or more) requests are two similar, don't hesitate to delete duplicate. @D-Maxwell if you want to make all requests to use your formatting, don't hesitate to do it.

### CODE REVIEW

**Review by D-Maxwell — CHANGES_REQUESTED** [review]
**Please avoid using fields other than ID to identify entries, such as in `request15.sql`.**

Although optional, titles ∨ a brief description of the request would befit them well. I guess it's fine for shorter requests not to have one.

**Comment by D-Maxwell** [comment]
Also request`n`.sql files may benefit from being named according to a two digit format (entirely optional once again)

**Comment by peotr26** [comment]
I have tested everything, and everything is working.

**Comment by peotr26** [comment]
> **Please avoid using fields other than ID to identify entries, such as in `request15.sql`.**
> 
> Although optional, titles ∨ a brief description of the request would befit them well. I guess it's fine for shorter requests not to have one.

That not mine, but checking it.

**Review by D-Maxwell — APPROVED** [review]
nvm this is fine

**Pull request merged**
