### PR TITLE
Merging the document with the tables, the schemes, etc

### PR DESCRIPTION
**Pull request by peotr26**
I have done the document that should be given to the professor.

### CODE REVIEW

**Comment by peotr26** [comment]
I have realized I have made a mistake. @D-Maxwell, I have also fixed the mistake on your database before merging it.

**Comment by D-Maxwell** [comment]
There are many occurrences of poorly named fields. I will correct them and propose the changes, to reflect that of the database.

**Comment by D-Maxwell** [comment]
Merging for now, see #14.

**Review by D-Maxwell — APPROVED** [review]

**Review by JeanChipo — COMMENTED** [review]
You forgot to add the restaurant affectation table in the table list (l5 -> l14) on the doc.md
Except that little mistake, everything seems good 👍

**Pull request merged**
